### ISSUE TITLE
processed data

### ISSUE THREAD

**Issue by tiam-22** [trinanjan12/Virtual-Try-on-#1]
Hello @trinanjan12 
Thanks for this great work, can you provide the processed data(e.g. semantic parsing, cloth mask).

**Comment by trinanjan12** [comment]
If you want to use the infamous viton data then you will get it online, only thing you gotta do is create densepose from using detectron2 densepose

If you want use your own data create segmentation using graphonomy. Cloth mask is a hard problem. If your clothing images has particular colour background then you can remove easily, like zalando images otherwise probably use grabcut. I haven't found something very effective

Note : This repo mostly follows the Original repo and instead of using keypoints i was using densepose to check if i get better results. I haven't worked on it for a while and not sure if everything works smoothly. You are most welcome to contribute

**Comment by trinanjan12** [comment]
If you want to use the infamous viton data then you will get it online, only thing you gotta do is create densepose from using detectron2 densepose

If you want use your own data create segmentation using graphonomy. Cloth mask is a hard problem. If your clothing images has particular colour background then you can remove easily, like zalando images otherwise probably use grabcut. I haven't found something very effective

Note : This repo mostly follows the Original repo and instead of using keypoints i was using densepose to check if i get better results. I haven't worked on it for a while and not sure if everything works smoothly. You are most welcome to contribute

**Comment by tiam-22** [comment]
Thanks a lot for your reply.
I want to use the MPV dataset, and I only get original data that including person and cloth mixed folder and a data_pair file. I would appreciate it if you could provide the processed data.

**Comment by trinanjan12** [comment]
check out this GitHub account. https://github.com/Yagami360/virtual-try-on_exercises_pytorch

**Comment by tiam-22** [comment]
Thank you very much.
But it is not MPV dataset. I need conduct experiments on the same dataset and compare the results with other papers(e.g. DOWN-TO-THE-LAST-DETAIL-VIRTUAL-TRY-ON-WITH-DETAIL-CARVING).

**Comment by trinanjan12** [comment]
Sorry, I am not currently working on this don't remember using the MPV dataset. I think I had tested it with yagami dataset or some data that I had scrapped. I was more interested to check out if densepose could make any difference!
